version: '2'
networks:
  kafka-tests_kafka-net:
    external: true
services:
  publisher:
    image: "event-tester:latest"
    networks:
      - kafka-tests_kafka-net
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
    env_file:
      - .env
    command: "bin/producer_tester_runner"
  kafka_consumer:
    image: "event-tester:latest"
    networks:
      - kafka-tests_kafka-net
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
    environment:
      - CONSUMER_NUMBER=1
    env_file:
      - .env
    command: bundle exec karafka s
