version: '2'
services:
  publisher:
    image: "kafka-publisher:latest"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
  consumer:
    image: "kafka-publisher:latest"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
    command: bash -c "sleep 20 && bundle exec karafka s"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
