version: '2'
networks:
  kafka-net:
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    networks:
      - kafka-net
    ports:
      - "4567-4597:4567-4597"
    environment:
      - SERVICES=sqs,sns,kinesis
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  kafka_setupper:
    image: "event-tester:latest"
    networks:
      - kafka-net
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
    environment:
      - CONSUMER_NUMBER=1
    env_file:
      - .env
    command: bundle exec ruby lib/kafka_tester/setupper.rb
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
